version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - dotnet restore ./basic-api-net6/basic-api-net6.csproj
      
  build:
    commands:
      - dotnet build ./basic-api-net6/basic-api-net6.csproj
      
  post_build:
    commands:
      - dotnet publish -c Release -r linux-x64 --self-contained false ./basic-api-net6/basic-api-net6.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./basic-api-net6/bin/Release/net6.0/linux-x64/publish
  discard-paths: no